export default {
  KO: {
    status: '진행상황',
    gameCount: '게임횟수',
    totalSpendMoney: '총 사용금액',
    genWinLottryNum: '당첨 로또 생성번호',
    genBuyLottryNum: '구입 로또 생성번호',
    language: '언어',
    langEn: '영어',
    langKo: '한국어',
    period: '기간',
    periodDesc: '일주일에 5장 구매',
    currency: '원',
    day: '일',
    month: '개월',
    year: '년',
    configLotteryNum: '로또번호 설정',
    numberRange: '숫자범위',
    numberCount: '숫자개수',
    winNumber: '당첨번호',
    buyNumber: '구입번호',
    correctionHistory: '적중기록',
    numberMatched: '자리 맞춤',
    count: '회',
    start: '시작',
    stop: '정지',
    reset: '초기화',
    auto: '자동',
    manual: '수동',
    selectDesc: '번호를 선택해 주세요',
    skipHistoryDesc: '낮은 적중은 기록을 하지 않습니다.',
  },
  EN: {
    status: 'Status',
    gameCount: 'Games',
    totalSpendMoney: 'Total money spent',
    genWinLottryNum: 'Winning numbers',
    genBuyLottryNum: 'Chosen numbers',
    language: 'Language',
    langEn: 'English',
    langKo: 'Korean',
    period: 'Period',
    periodDesc: '5 Tries per week',
    currency: 'USD',
    day: 'Days',
    month: 'Months',
    year: 'Years',
    configLotteryNum: 'Lottery Number Setting',
    numberRange: 'Range',
    numberCount: 'Number Count',
    winNumber: 'Winning Numbers',
    buyNumber: 'Chosen Numbers',
    correctionHistory: 'Matching History',
    numberMatched: 'matched',
    count: 'times',
    start: 'Start',
    stop: 'Stop',
    reset: 'Reset',
    auto: 'Auto',
    manual: 'Manual',
    selectDesc: 'Select Numbers',
    skipHistoryDesc: 'Low matching numbers are not written',
  },
};
